image: mcr.microsoft.com/dotnet/sdk:6.0

stages:
    - build

workflow:
    rules:
        - if: $CI_MERGE_REQUEST_ID             # Execute jobs in merge request context
        - if: $CI_COMMIT_BRANCH == 'main'      # Execute jobs when a new commit is pushed to main branch

build:
    stage: build
    script:
        - "dotnet build --configuration=Release"
